# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160811_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lastmod',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
