# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 11:46
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.models.Person.profile_photo_path),
        ),
    ]
