# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160812_1213'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('Au', 'Author'), ('Ed', 'Editor'), ('Ad', 'Advisor'), ('Re', 'Referee'), ('Tr', 'TRANSLATOR')], max_length=2)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('milestone_type', models.CharField(choices=[('D', 'Deposited'), ('L', 'Live'), ('A', 'Accepted'), ('P', 'Published')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publicationtype',
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='divisions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='lastmod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_status',
            field=models.CharField(choices=[('S', 'Submitted'), ('A', 'Accepted'), ('P', 'Published'), ('I', 'In Press'), ('U', 'Unpublished')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('A', 'Article'), ('B', 'Book'), ('S', 'Book Section')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='publication',
            name='revision',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('I', 'inbox'), ('B', 'buffer'), ('A', 'archive'), ('D', 'deletion')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='publication',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='visibility_status',
            field=models.CharField(choices=[('P', 'Public'), ('R', 'Restricted'), ('E', 'Embagoed'), ('N', 'None')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='publication',
            name='depositor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
