# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20160812_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
