# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20161212_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
