# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='accept_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='online_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
